name: CI & Deploy

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-test-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js with pnpm
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: pnpm

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Install dependencies
        run: pnpm install

      - name: Run tests with coverage
        run: pnpm test --coverage

      - name: Build Vite App
        run: pnpm build

      - name: Deploy Vite site to GitHub Pages
        if: github.ref == 'refs/heads/main'
        run: |
          git config --global user.email "ci@github.com"
          git config --global user.name "GitHub CI"
          pnpm run deploy